
services:
  app:
    container_name: taskforge-backend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules
    command: npx tsx src/server.ts
    depends_on:
      - db
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:15
    container_name: taskforge-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  db_test:
    image: postgres:15
    container_name: taskforge-db-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
